---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: config/_ytt_lib
  contents:
  - path: github.com/GoogleCloudPlatform/metacontroller
    git:
      url: https://github.com/GoogleCloudPlatform/metacontroller
      ref: v0.4.0
    includePaths:
    - manifests/*
  - path: github.com/cloudfoundry/cf-k8s-networking
    git:
      url: https://github.com/cloudfoundry/cf-k8s-networking
      ref: b4375d0b13cb853ee402a9530b54188772c24ff6
    includePaths:
    - cfroutesync/crds/**/*
    - config/cfroutesync/**/*
  - path: github.com/cloudfoundry/capi-k8s-release
    git:
      url: https://github.com/cloudfoundry/capi-k8s-release
      ref: 4ec231cbbabbe0a90ac25c0b49daa2b407df85c6
    includePaths:
    - templates/**/*
    - values.yml
  - path: istio
    manual: {}
  - path: eirini
    manual: {}
