#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-api-server
  namespace: cf-system
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: capi-api-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: capi-api-server
    spec:
      #@ if/end data.values.imagePullSecrets:
      imagePullSecrets: #@ data.values.imagePullSecrets
      initContainers:
        - name: pre-start
          image: localhost:5000/capi
          imagePullPolicy: Always
          command:
          - /cloud_controller_ng/pre-start.sh
          volumeMounts:
          - name: cloud-controller-ng-yaml
            mountPath: /config
      containers:
        - name: capi-api-server
          image: localhost:5000/capi
          imagePullPolicy: Always
          volumeMounts:
          - name: server-sock
            mountPath: /data/cloud_controller_ng
          - name: cloud-controller-ng-yaml
            mountPath: /config/
          #@ if/end data.values.uaa.serverCerts.secretName:
          - name: uaa-certs
            mountPath: /config/uaa/certs
          #@ if/end data.values.eirini.serverCerts.secretName:
          - name: eirini-certs
            mountPath: /config/eirini/certs
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          volumeMounts:
          - name: nginx
            mountPath: /etc/nginx
            readOnly: true
          - name: server-sock
            mountPath: /data/cloud_controller_ng
          - name: nginx-logs
            mountPath: /cloud_controller_ng
      volumes:
      - name: server-sock
        emptyDir: {}
      - name: cloud-controller-ng-yaml
        configMap:
          name: cloud-controller-ng-yaml
      - name: nginx
        configMap:
          name: nginx
      - name: nginx-logs
        emptyDir: {}
      #@ if/end data.values.uaa.serverCerts.secretName:
      - name: uaa-certs
        secret:
          secretName: #@ data.values.uaa.serverCerts.secretName
      #@ if/end data.values.eirini.serverCerts.secretName:
      - name: eirini-certs
        secret:
          secretName: #@ data.values.eirini.serverCerts.secretName

