#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-clock
  namespace: cf-system
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: capi-clock
  template:
    metadata:
      labels:
        app.kubernetes.io/name: capi-clock
    spec:
      #@ if/end data.values.imagePullSecrets:
      imagePullSecrets: #@ data.values.imagePullSecrets
      containers:
        - name: capi-clock
          workingDir: "/cloud_controller_ng"
          command: ["/usr/local/bin/bundle"]
          args: ["exec", "rake", "clock:start"]
          image: localhost:5000/capi
          imagePullPolicy: Always
          volumeMounts:
          - name: cloud-controller-ng-yaml
            mountPath: /config
          - name: opi-secrets
            mountPath: /config/opi/certs
      volumes:
      - name: cloud-controller-ng-yaml
        configMap:
          name: cloud-controller-ng-yaml
      - name: opi-secrets
        secret:
          secretName: opi-secrets
